HIARC-Developers/HIARC-Platform-FE

packages/ui/src/components/button.tsx

Button 컴포넌트 구현
<br/>
- Button 컴포넌트 구현
- 다음 항목들을 기준으로 구현
- variant: fill, secondary, line
- size: xs, sm, md, lg, xl
<br/>
주요 변경 사항과 동일
<br/>
- #1
<br/>
tailwind-css 설정이 미흡한 상태이기에 tailwind-css 설정을 마친 후 수정할 예정입니다.

Feat: Button 컴포넌트

---

packages/ui/src/components/label.tsx
packages/ui/src/components/title.tsx
packages/ui/src/index.ts

Label 컴포넌트 구현
<br/>
- Label 컴포넌트 구현
- 다음 항목들을 기준으로 구현
- size: xs, sm, md, lg
- weight: normal, medium, semibold, bold
<br/>
주요 변경 사항과 동일
<br/>
- #1
<br/>
tailwind-css 설정이 미흡한 상태이기에 tailwind-css 설정을 마친 후 수정할 예정입니다.

Feat: Label 컴포넌트

---

packages/ui/src/components/label.tsx
packages/ui/src/components/title.tsx

수정된 tailwind-css에 맞게 Label, Title 컴포넌트 수정
<br/>
- Label의 md variant에서 text-base를 text-md로 수정
- Title의 sm variant의 크기를 3xl에서 2xl로 수정
<br/>
Label의 md variant에서 text-base를 text-md로 수정했고, Title의 sm variant의 크기를 3xl에서 2xl로 수정했습니다.
<br/>
- #1
<br/>

Fix: 수정된 tailwind-css에 맞게 Label, Title 컴포넌트 수정

---

packages/ui/src/components/button.tsx

수정된 tailwind-css에 맞게 버튼 스타일링 수정
<br/>
- fill 색상을 primary에서 primary-300으로 변경
- line의 색상을 primary에서 primary-300으로 변경
- 호버 효과 추가
<br/>
색상 수정과 호버 효과를 추가했습니다.
호버 효과로는 위로 살짝 뜨는 효과를 추가했습니다.
<br/>
- #1
<br/>

Fix: 수정된 tailwind-css에 맞게 버튼 스타일링 수정

---

apps/intra/constants/selectOption.ts
apps/intra/src/app/signup/page.tsx
apps/intra/src/ui/Header.tsx
apps/intra/src/ui/ToggleSelector.tsx
packages/ui/src/components/select.tsx
packages/ui/src/index.ts

ToggleSelector 개발 ex)학년 ,학과 선택 selector
(근데 하고보니 이름을  토글말고 다른걸로 할 걸 그런 것 같아요)
<br/>
- ToggleSelector 개발
- SelectContents 파일에 선택창이 내려가면 겹쳐보이던 현상->bg-white로 수정
- SignUp페이지 생성 : Test용
<br/>
- ToggleSelector 개발
- SelectContents 파일에 선택창이 내려가면 겹쳐보이던 현상->bg-white로 수정
- SignUp페이지 생성 : Test용
<br/>
- #N
<br/>

Feat:  ToggleSelector 개발

---

apps/intra/src/app/signup/page.tsx
packages/ui/src/components/button.tsx
packages/ui/src/components/input/input.tsx
packages/ui/src/components/input/labeled-input.tsx
packages/ui/src/components/select/labeled-select-button.tsx
packages/ui/src/components/select/labeled-selector.tsx
packages/ui/src/index.ts

- LabeledSelectButton 구현
- signup 페이지 조립
<br/>
- LabeledSelectButton을 구현했습니다.
- signup 페이지를 조립했습니다.
- button 컴포넌트에 unselected 라는 variation을 추가하였습니다.(disabled는 이벤트 캐치가 안돼서 따로 만들었어요)
<br/>
- LabeledSelectButton을 구현
- signup 페이지 조립
<br/>
- #N
<br/>

Feat: LabeledSelectButton 구현

---

apps/admin/src/features/manage/manage-tab-section/recruit-manage-section/index.tsx

모집관리 학회원 없을때 화면 구현 
<br/>
- 모집관리 학회원 없을때 화면 구현 
<br/>
- 모집관리 학회원 없을때 화면 구현 
<br/>
- #N
<br/>

Feat: 모집관리 학회원 없을때 화면 구현 

---

apps/admin/src/stores/semester-store.ts
apps/intra/src/stores/semester-store.ts

학기 정보를 불러오지 못하는 오류 수정
<br/>
- 학기 정보를 불러오지 못하는 오류 수정
<br/>
학기 정보를 불러오지 못하는 오류 수정
<br/>
- 없음
<br/>

Fix: 학기 정보를 불러오지 못하는 오류 수정

---

apps/admin/src/features/auth/hooks/use-google-login.ts
apps/admin/src/features/auth/pages/login-page/login-page.tsx
apps/admin/src/features/member/components/manage-tab-section/recruit-manage-section/index.tsx
apps/admin/src/features/member/components/member-recruit-table/approval-button.tsx
apps/admin/src/features/member/components/member-recruit-table/index.tsx
apps/admin/src/features/member/components/member-recruit-table/student-apply-list-column.tsx
apps/admin/src/shared/utils/browser-utils.ts
apps/intra/src/features/auth/hooks/callback/use-google-login.ts
apps/intra/src/features/auth/pages/login/desktop-login-page.tsx
apps/intra/src/features/auth/pages/login/mobile-login-page.tsx
apps/intra/src/shared/utils/browser-utils.ts
packages/shared/src/types/recruit/recruitment.ts

인앱 브라우저 환경에서 Google 로그인을 제한하는 BrowserUtils 도입
관리자 및 인트라 앱의 로그인 페이지에서 인앱 브라우저 접근 시 경고 표시
새로운 모집 상태 및 승인 버튼 가시성 지원을 위한 모집 타입 및 멤버 모집 테이블 로직 리팩토링
<br/>
- 인앱 브라우저 환경에서 Google 로그인을 제한하는 BrowserUtils 도입
- 관리자 및 인트라 앱의 로그인 페이지에서 인앱 브라우저 접근 시 경고 표시
- 새로운 모집 상태 및 승인 버튼 가시성 지원을 위한 모집 타입 및 멤버 모집 테이블 로직 리팩토링
<br/>
인앱 브라우저 환경에서 Google 로그인을 제한하는 BrowserUtils 도입
관리자 및 인트라 앱의 로그인 페이지에서 인앱 브라우저 접근 시 경고 표시
새로운 모집 상태 및 승인 버튼 가시성 지원을 위한 모집 타입 및 멤버 모집 테이블 로직 리팩토링
<br/>
<br/>

Fix: 모집 상태 및 승인 버튼 수정

---

apps/admin/next.config.mjs
apps/admin/src/shared/api/client.ts
apps/admin/src/shared/utils/browser-utils.ts
apps/admin/src/shared/utils/cookie-utils.ts
apps/intra/next.config.js
apps/intra/src/shared/api/client.ts
apps/intra/src/shared/utils/browser-utils.ts
apps/intra/src/shared/utils/cookie-utils.ts
apps/intra/vercel.json
packages/shared/package.json
packages/ui/package.json
packages/ui/src/index.ts
packages/util/package.json

- 브라우저 및 쿠키 유틸리티에 서버사이드 체크 추가로 SSR 오류 방지
- 액세스 토큰 쿠키 삭제 시 더 많은 도메인/경로 조합 처리 및 비프로덕션 환경에서만 디버그 로깅 활성화
- @hiarc-platform/shared 트랜스파일을 위한 Next.js 설정 업데이트
- package.json 파일의 main/types 필드 수정 및 인트라 Vercel 배포 설정 추가
- UI 패키지에서 create-study-form 컴포넌트 재내보내기
<br/>
- 브라우저 및 쿠키 유틸리티에 서버사이드 체크 추가로 SSR 오류 방지
- 액세스 토큰 쿠키 삭제 시 더 많은 도메인/경로 조합 처리 및 비프로덕션 환경에서만 디버그 로깅 활성화
- @hiarc-platform/shared 트랜스파일을 위한 Next.js 설정 업데이트
- package.json 파일의 main/types 필드 수정 및 인트라 Vercel 배포 설정 추가
- UI 패키지에서 create-study-form 컴포넌트 재내보내기
<br/>
브라우저 및 쿠키 유틸리티에 서버사이드 체크 추가로 SSR 오류 방지
액세스 토큰 쿠키 삭제 시 더 많은 도메인/경로 조합 처리 및 비프로덕션 환경에서만 디버그 로깅 활성화
@hiarc-platform/shared 트랜스파일을 위한 Next.js 설정 업데이트
package.json 파일의 main/types 필드 수정 및 인트라 Vercel 배포 설정 추가
UI 패키지에서 create-study-form 컴포넌트 재내보내기
<br/>
<br/>

refactor: SSR 안전성 개선 및 공유 유틸리티 로깅 강화

---

apps/admin/src/features/member/hooks/member/query/use-download-excel.ts
apps/admin/src/features/recruitment/hooks/mutation/use-download-applicant-excel.ts
apps/admin/src/shared/utils/browser-utils.ts
apps/intra/src/shared/utils/browser-utils.ts

fix: admin 빌드 문제 해결

---

apps/admin/src/features/member/components/manage-tab-section/recruit-manage-section/index.tsx
pnpm-lock.yaml

Fix: 페이지네이션 오류 수정

---

apps/admin/public/shared-assets/Hamburger.svg
apps/admin/src/app/announcement/[id]/edit/layout.tsx
apps/admin/src/app/announcement/write/layout.tsx
apps/admin/src/features/announcement/components/announcement-table/mobile-more-menu.tsx
apps/admin/src/features/announcement/pages/announcement-write-page/announcement-write-page.tsx
apps/admin/src/shared/components/ConditionalHeader.tsx
apps/intra/public/shared-assets/Hamburger.svg
apps/intra/src/features/main/components/announcement-list-section/announcement-list-item.tsx
apps/intra/src/features/main/components/announcement-list-section/index.tsx
apps/intra/src/features/main/components/hiarc-schedule-section/index.tsx
packages/ui/src/components/header/mobile-header.tsx
packages/ui/src/components/header/mobile-menu.tsx
packages/ui/src/components/layout/page-layout.tsx
public/Hamburger.svg
tailwind.config.js

어드민 및 인트라 앱 전반의 일관성, 유용성, 코드 명확성을 위한 UI 및 코드 개선 작업입니다.
<br/>
- 모바일 메뉴 컴포넌트 리팩토링 및 헤더/메뉴 디자인 개선
- 공지사항 목록 레이아웃 및 정렬 로직 개선
- 메뉴 항목 레이블 및 정렬 순서 조정
<br/>
- **UI 컴포넌트 및 레이아웃 개선:**
- `mobile-more-menu.tsx`에서 `Button` 컴포넌트를 네이티브 `button` 요소와 `Label`로 대체하여 접근성 및 스타일 개선, 이벤트 핸들러 타입 명확화
- `announcement-list-item.tsx`의 공지사항 목록 아이템 레이아웃을 개선하여 텍스트 잘림, 정렬 및 반응성 문제 해결
- **헤더 및 메뉴 시각적 개선:**
- `mobile-header.tsx`에서 모바일 헤더 메뉴 아이콘을 'Menu.svg'에서 'Hamburger.svg'로 변경
- `mobile-menu.tsx`에서 닫힌 상태일 때 빈 `div`를 사용하도록 변경하고, 메뉴 항목 레이블의 글꼴 크기 및 굵기를 키워 가독성 향상
- **내비게이션 및 메뉴 레이블 변경:**
- `ConditionalHeader.tsx`에서 메뉴 항목 순서를 재정렬하고 '학회원 관리'를 우선시하도록 변경
- **로직 및 타입 개선:**
- `announcement-list-section/index.tsx`에서 다가오는 일정 정렬 로직을 가독성 및 유지보수성을 고려하여 개선
- 레이아웃 및 페이지 컴포넌트가 `React.ReactElement`를 명시적으로 반환하도록 하고, 이벤트 핸들러 타입을 명확화하여 타입 …

Refactor: UI 및 코드 개선 작업

---

apps/admin/src/features/study/components/create-study-form-section/create-study-form.tsx
apps/admin/src/features/study/components/tab-section/lecture-list.tsx
apps/intra/src/features/study/components/edit-study-form/index.tsx
apps/intra/src/features/study/components/tab-section/lecture-list.tsx
apps/intra/src/features/study/types/request/create-study-request.ts
packages/shared/src/types/study/create-study-request.ts
packages/shared/src/types/study/study-initial-form.ts

Admin 페이지 출석 모달 수정
스터디장 출석번호 확인 모달 수정
isGroupStudy Props 추가
<br/>
- Admin 페이지 출석 모달 수정
- 스터디장 출석번호 확인 모달 수정
- isGroupStudy Props 추가
<br/>
- Admin 페이지 출석 모달 수정
- 스터디장 출석번호 확인 모달 수정
- isGroupStudy Props 추가
<br/>
- #N
<br/>

Feat: Admin 페이지 출석 모달 수정, 스터디장 출석번호 확인 모달 수정 , isGroupStudy Props 추가

---

apps/intra/src/features/study/pages/study-detail/mobile-study-detail-page.tsx
packages/ui/src/components/study/mobile-study-button.tsx
packages/ui/src/components/study/study-info-section/study-title.tsx
packages/ui/src/index.ts

모바일 스터디 신청 버튼 구현했습니다
Admin 에서 스터디 신청 뜨는 문제 해결했습니다
<br/>
- 모바일 스터디 신청 버튼 구현
- Admin 에서 스터디 신청 뜨는 문제 해결
- ...
<br/>
모바일 스터디 버튼을 따로 만들어서 모바일 환경일때 D-{신청끝나는기간-현재시간} 을 해서 남은기간을 표시하게 만들었습니다.
Admin에서 스터디 신청이 뜨는 문제를 isAdmin이 아닐때만 렌더링하는 로직을 추가하였습니다
<br/>
- #N
<br/>

Feat:  모바일 스터디 신청 버튼 구현,Admin 에서 스터디 신청 뜨는 문제 해결

---

apps/intra/src/features/member/components/my-info-section/index.tsx

my페이지에서 핸들을 누르면 solved.ac로 이동합니다
<br/>
- my페이지에서 핸들을 누르면 solved.ac로 이동합니다
<br/>
- my페이지에서 핸들을 누르면 solved.ac로 이동합니다
<br/>
- #N
<br/>

Feat: 핸들누르면 solved.ac로 이동

---

apps/admin/src/features/study/components/tab-section/announcement-table.tsx
apps/admin/src/features/study/components/tab-section/create-assignment-dialog-wrapper.tsx
apps/admin/src/features/study/components/tab-section/lecture-list.tsx
apps/admin/src/features/study/hooks/use-assignment.ts
apps/intra/src/features/announcement/pages/announcement-edit/desktop-announcement-edit-page.tsx
apps/intra/src/features/announcement/pages/announcement-edit/mobile-announcement-edit-page.tsx
apps/intra/src/features/announcement/pages/announcement-write/desktop-announcement-write-page.tsx
apps/intra/src/features/announcement/pages/announcement-write/mobile-announcement-write-page.tsx
apps/intra/src/features/study/api/study-instructor.ts
apps/intra/src/features/study/components/study-search-section/index.tsx
apps/intra/src/features/study/components/study-search-section/study-search-dialog.tsx
apps/intra/src/features/study/components/study-table/index.tsx
apps/intra/src/features/study/components/tab-section/announcement-table.tsx
apps/intra/src/features/study/components/tab-section/index.tsx
apps/intra/src/features/study/components/tab-section/lecture-list.tsx
apps/intra/src/features/study/hooks/study-instructor/mutation/use-check-assignment.ts
apps/intra/src/features/study/pages/study-detail/mobile-study-detail-page.tsx
apps/intra/src/features/study/pages/study-list/mobile-study-list-page.tsx
apps/intra/src/shared/components/ui/ConditionalHeaderClient.tsx
apps/intra/src/shared/components/ui/Footer.tsx
packages/shared/src/types/study/assignment.ts
packages/ui/src/components/chip/study-status-chip.tsx
packages/ui/src/components/study/create-assignment-dialog.tsx
packages/ui/src/components/study/create-attendance-code-dialog.tsx
packages/ui/src/components/study/lecture-list-item.tsx
packages/ui/src/components/study/student-list-item.tsx
packages/ui/src/components/study/study-info-section/study-title.tsx

스터디 및 공지사항 관리 기능에 대한 여러 UI 및 기능적 개선사항을 도입하여 향상된 모바일 및 데스크톱 경험, 코드 간소화, 새로운 강사 기능 구현
통합 헤더 컴포넌트를 사용하도록 공지사항 편집/작성 페이지 리팩토링, 더 나은 모바일 사용성을 위한 스터디 검색 및 테이블 컴포넌트 재설계, 강사가 과제 상태를 확인할 수 있는 API 엔드포인트 추가
<br/>
- 새로운 `AnnouncementDesktopHeader` 컴포넌트를 사용하도록 공지사항 편집/작성 페이지 리팩토링
- 모바일 접근성 및 레이아웃 개선을 위한 스터디 검색 다이얼로그 및 버튼 재설계
- `Label` 및 `StudyStatusChip` 컴포넌트를 사용한 모바일 친화적 스터디 테이블 리스트 뷰 업데이트
- 강사용 과제 상태 확인을 위한 새로운 `CHECK_ASSIGNMENT` API 엔드포인트 추가
- 사용하지 않는 props 및 컴포넌트 제거로 코드 간소화
<br/>
**UI/UX 개선**
- 중복된 헤더 로직 제거 및 페이지 구조 간소화를 위해 새로운 `AnnouncementDesktopHeader` 컴포넌트를 사용하도록 데스크톱 및 모바일 공지사항 편집/작성 페이지 리팩토링
- `Label` 컴포넌트 사용 및 더 나은 스크롤링과 버튼 배치를 위한 다이얼로그 콘텐츠 재구성으로 모바일용 스터디 검색 다이얼로그 및 버튼 재설계하여 접근성과 레이아웃 개선
- `Label` 및 `StudyStatusChip` 컴포넌트를 사용하여 개선된 네비게이션 및 상태 표시가 포함된 모바일 친화적 리스트 뷰 제공하도록 스터디 테이블 업데이트
**기능적 …

Fix: 스터디 모바일 뷰 보강

---

apps/intra/src/shared/components/ui/header/authenticated-user-section.tsx

모집 중 로직 해제
<br/>
- 헤더의 마이페이 진입 시, 모집 중 로직 해제
<br/>
<br/>
- #122 
<br/>

Fix: 모집 중 로직 해제

---

apps/intra/src/features/main/components/announcement-list-section/AnnouncementListItem.tsx
apps/intra/src/features/main/components/announcement-list-section/AnnouncementListSection.tsx
apps/intra/src/features/main/components/announcement-list-section/RatingListItem.tsx
apps/intra/src/features/main/components/study-list-section/index.tsx
apps/intra/src/features/main/pages/home/desktop-home-page.tsx
apps/intra/src/features/main/pages/home/mobile-home-page.tsx
packages/shared/src/util/date-util.ts
packages/ui/src/components/layout/content-section.tsx

공지사항 목록 섹션 컴포넌트를 리팩토링하고 코드 구성을 개선하며 UI 일관성을 향상
레이팅 공지사항 전용 `RatingListItem` 컴포넌트 도입, 로직 간소화를 위한 `isEvent` prop 제거, 현지화 개선을 위한 날짜 형식 업데이트
<br/>
- 레이팅 관련 공지사항 처리를 위한 새로운 `RatingListItem` 컴포넌트 도입
- `AnnouncementListItem`에서 `isEvent` prop 제거로 로직 간소화
- 한국어 스타일 날짜 형식을 위한 새로운 유틸리티 함수 `DateUtil.formatKoreanDate` 추가
- 명시적 파일 이름 사용으로 공지사항 목록 섹션 컴포넌트 임포트 업데이트
- 액션 버튼에 패딩 및 호버 효과 추가로 사용자 경험 향상
<br/>
**컴포넌트 리팩토링 및 코드 구성**
- 일반 공지사항과 분리하여 레이팅 관련 공지사항을 처리하는 새로운 `RatingListItem` 컴포넌트(`apps/intra/src/features/main/components/announcement-list-section/RatingListItem.tsx`) 도입으로 렌더링 로직 간소화 및 유지보수성 향상
- `AnnouncementListItem`에서 `isEvent` prop 제거 및 사용법 업데이트로 컴포넌트를 간소화하고 모든 공지사항 항목을 일관되게 클릭 가능하도록 설정
- 코드 명확성 향상 및 모호함 감소를 위해 공지사항 목록 섹션 컴포넌트의 임포트를 명시적 파일 이름 사용으로 이름 변경 및 업데이트
**UI 및 레이아웃 개선**
- 사용자 경험과 시각적 일관성 향상을 …

refactor: 공지사항 목록 섹션 리팩토링 및 RatingListItem 추가 #138

---

apps/rating/src/api/AdminApi.ts
apps/rating/src/block/adminBlock/AdminInput.tsx
apps/rating/src/block/streak/DinamicStreakBox.tsx
apps/rating/src/block/streak/NewStreakEntity.tsx
apps/rating/src/block/streak/StreakInformation.tsx
apps/rating/src/page/AdminPage.tsx
apps/rating/src/page/StreakPage.tsx
apps/rating/src/util/AdminExplain.ts

StreakPage 모바일뷰 구현
현재 시즌 수정 -> 시즌 정보 수정
<br/>
- 스트릭 페이지 모바일 뷰를 구현했습니다.
- 현재시즌 수정 을 시즌 정보 수정으로 바꾸었습니다.
- ...
<br/>
- 스트릭 페이지 모바일 뷰를 구현했습니다.
- 현재시즌 수정 을 시즌 정보 수정으로 바꾸었습니다.
<br/>
- #N
<br/>

Feat: Rating 디자인 변경

---

apps/intra/src/shared/components/ui/header/desktop-header.tsx
apps/intra/src/shared/components/ui/header/mobile-header.tsx
packages/ui/src/components/input/input.tsx

헤더 컴포넌트의 오류 처리 및 인증 확인을 개선, 검색 입력 필드 UI 향상
오류 로깅 추가, 모바일 헤더 UI 요소의 인증 로직 개선, 더 나은 성능을 위해 검색 입력에 Next.js `Image` 컴포넌트 사용 업데이트
<br/>
- 디버깅 지원을 위해 `DesktopHeader`와 `MobileHeader` 컴포넌트에 회원 ID 가져오기 실패에 대한 오류 로깅 추가
- 인증된 사용자에게만 모바일 헤더 검색 버튼이 렌더링되도록 업데이트
- 중복된 인증 확인을 제거하여 검색 버튼 클릭 핸들러 로직 간소화
- 성능 및 일관성 향상을 위해 `Input` 컴포넌트의 검색 아이콘을 Next.js `Image`로 교체
- `type="search"` 및 `variant="search"` 입력 모두에서 검색 아이콘이 렌더링되도록 개선
<br/>
**오류 처리 개선**
- 디버깅을 지원하기 위해 `DesktopHeader`와 `MobileHeader` 컴포넌트 모두에서 회원 ID 가져오기 실패에 대한 `console.error` 로깅 추가
**인증 및 UI 로직 업데이트**
- 인증된 사용자에게만 렌더링되도록 모바일 헤더 검색 버튼 업데이트
- 중복된 인증 확인을 제거하여 클릭 핸들러 로직 간소화
**UI 및 성능 향상**
- 성능과 일관성 향상을 위해 `Input` 컴포넌트의 검색 아이콘에 표준 `<img>` 태그 대신 Next.js `Image` 사용
- `type="search"` 및 `variant="search"` 입력 모두에서 검색 아이콘이 렌더링되도록 개선
<br/>
- #153
<br/>

Fix: 로그인 된 상태가 아니면 검색 버튼이 아예 안보이게 수정

---

MONOREPO_GUIDE.md
apps/intra/src/app/announcement/[id]/loading.tsx
apps/intra/src/app/announcement/[id]/page.tsx
apps/intra/src/features/announcement/pages/announcement-detail/components/announcement-navigation-section.tsx
apps/intra/src/features/announcement/pages/announcement-detail/desktop-announcement-detail-page.tsx
apps/intra/src/features/announcement/pages/announcement-detail/mobile-announcement-detail-page.tsx
packages/ui/src/components/announcement/announcement-indicator-section/announcement-indicator-section.tsx
packages/ui/src/components/announcement/announcement-info-section/application-button.tsx
packages/ui/src/components/announcement/announcement-info-section/location-schedule-section.tsx
pnpm-lock.yaml

`intra` 앱의 공지사항 상세 페이지에 대한 대규모 개선 작업. 서버 사이드 데이터 페칭, UI 리팩토링, 코드 모듈화를 통해 성능과 유지보수성 향상. 모노레포 가이드 문서 추가
<br/>
- 공지사항 상세 페이지 서버 사이드 데이터 페칭 및 정적 생성(SSG) 지원
- 네비게이션 섹션 컴포넌트 분리 및 재사용성 개선
- 상세 페이지 컴포넌트 리팩토링 및 상태 관리 단순화
- 신청하기 버튼 모듈화
- 로딩 상태 처리 컴포넌트 추가
- 모노레포 가이드 문서 작성
<br/>
**공지사항 상세 페이지 리팩토링 및 데이터 페칭:**
- 공지사항 상세 페이지(`[id]/page.tsx`)에서 서버 사이드로 `announcementApi`를 사용한 데이터 페칭 구현
- `generateStaticParams`를 통한 정적 페이지 생성(SSG) 지원으로 성능 및 SEO 개선
- Not-found 케이스 처리 로직 추가
- 기존 클라이언트 사이드 데이터 페칭 로직 제거
- 전용 로딩 컴포넌트(`[id]/loading.tsx`) 추가로 데이터 로딩 중 사용자 경험 개선
**컴포넌트 리팩토링 및 모듈화:**
- 네비게이션 컨트롤(뒤로가기 버튼, "목록으로" 버튼)을 `AnnouncementNavigationSection` 컴포넌트로 분리
- 데스크톱 및 모바일 상세 페이지에서 재사용 가능한 네비게이션 섹션 적용
- 데스크톱(`desktop-announcement-detail-page.tsx`)과 모바일(`mobile-announcement-detail-page.tsx`) 상세 페이지 컴포넌트를 props로 공지사항 …

refactor: 공지사항 상세 페이지 리팩토링 및 네비게이션 추가 #156
